SELECT ID, TYPE, FEE
FROM (
    SELECT c.CAR_ID AS ID, c.CAR_TYPE AS TYPE, ROUND(c.DAILY_FEE * 30 * (1- p.DISCOUNT_RATE / 100.0)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE
    WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
    AND p.DURATION_TYPE = '30일 이상'
    AND c.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
) AS r
WHERE 500000 <= r.FEE AND r.FEE < 2000000
ORDER BY FEE DESC, TYPE, ID DESC