SELECT 
    e.ID,
    CASE
        WHEN e.RK <= COUNT(*) OVER() * 0.25 THEN 'CRITICAL'
        WHEN e.RK <= COUNT(*) OVER() * 0.5 THEN 'HIGH'
        WHEN e.RK <= COUNT(*) OVER() * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RK
    FROM ECOLI_DATA
) AS e
ORDER BY e.ID;