SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, 
    ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW r NATURAL JOIN REST_INFO i 
WHERE i.ADDRESS LIKE '서울%'
GROUP BY r.REST_ID
ORDER BY SCORE DESC, i.FAVORITES DESC