SELECT f.FLAVOR
FROM FIRST_HALF f JOIN (
    SELECT JULY.SHIPMENT_ID, JULY.FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS j
ON f.SHIPMENT_ID = j.SHIPMENT_ID AND f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.TOTAL_ORDER) DESC
LIMIT 3;
