-- 코드를 입력하세요
SELECT b.TITLE AS TITLE, 
b.BOARD_ID AS BOARD_ID, 
r.REPLY_ID AS REPLY_ID, 
r.WRITER_ID AS WRITER_ID, 
r.CONTENTS AS CONTENTS, 
SUBSTRING(r.CREATED_DATE, 1, 10) AS CREATED_DATE
FROM USED_GOODS_BOARD AS b INNER JOIN USED_GOODS_REPLY AS r 
ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE like '2022-10-%'
ORDER BY r.CREATED_DATE, b.TITLE;

# SELECT *
# FROM USED_GOODS_BOARD