SELECT b.CATEGORY AS CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y.%m') = '2022.01'
) AS bs LEFT JOIN BOOK AS b 
ON bs.BOOK_ID = b.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;
